Revert "AttributeError: 'ParentAlternativelyMappedMapping' object has no attribute 'level_one_attribute'"
This reverts commit 4f752c6257b37d6520ece141636a9b3c58d29fa5.